add Azure's OpenAI support; updated to latest ruby-openai
merefield/discourse-chatbot pull request #24
Opened 2023-07-08 02:54 UTC by fokx

* add Azure's OpenAI support
    * add custom endpoint URL in settings, in a similar way as how `discourse-ai` use Azure
    * Azure-related configurations done with `OpenAI.configure` in `bots/open_ai_bot.rb` `initialize`
* update `ruby-openai` to latest version
    * add its dependencies `faraday` and remove `httparty`
    * change response.parsed_response["key"] to just response["key"] (see `ruby-openai`'s [CHNAGELOG](https://github.com/alexrudall/ruby-openai/blob/main/CHANGELOG.md))

2023-07-08 03:10 UTC, fokx commented
The Azure OpenAI application and deployment can be a little cumbersome, but I do managed to get the Azure version of gpt3.5-turbo-16k chatbot work on my forum.

2023-08-02 12:49 UTC, merefield commented
I've merged an update which now uses 4.2.0 so some of these changes are redundant ... please merge in main.

2023-08-03 04:45 UTC, fokx commented
OK, I have merged branch your 'main' into my 'support-azure-openai' branch.

2023-08-05 11:08 UTC, merefield requested changes

2023-08-05 11:10 UTC, merefield commented on plugin.rb
> +gem 'faraday', '2.7.10', {require: false }
this appears to have been addressed, resolving.

2023-08-05 14:19 UTC, fokx commented on config/locales/server.en.yml
> +    chatbot_openai_gpt4_url: "Modify it if you want to use GPT 4 by Azure, e.g. https://custom-domain.openai.azure.com/openai/deployments/DEPLOYMENT)."
When deploying GPT 3.5 / GPT 4 model in Azure's AI Studio, the `<CUSTOM_DEPLOYMENT>` part in the URL is also customizable.
So I think it is necessary to separate these to two different setting names.

PS: Azure OpenAI's URL is `https://<CUSTOM_SUBDOMAIN>.openai.azure.com/openai/deployments/<CUSTOM_DEPLOYMENT>`

2023-08-05 14:21 UTC, fokx commented on config/settings.yml
> +  chatbot_openai_gpt4_url: "https://api.openai.com/v1/chat/completions"
Yeah, it is truly a duplication for OpenAI's API, but not for Azure's.

2023-08-05 14:22 UTC, fokx commented on plugin.rb
> +                            .root
OK, I will use rubocop. I previously used RubyMine's `Alt+Shift+L` reformating.

2023-08-14 15:36 UTC, merefield commented on config/locales/server.en.yml
> +    chatbot_openai_gpt4_url: "Modify it if you want to use GPT 4 by Azure, e.g. https://custom-domain.openai.azure.com/openai/deployments/DEPLOYMENT)."
I think we could expect the user to change the URI setting if they change model, no?  The danger is other models will be released and are you planning on having even more settings to accommodate each and every released model?  I would be much more comfortable here with one setting, e.g. `chatbot_openai_azure_url` and require the user to update that as well as the model choice if required.

2023-08-14 15:37 UTC, merefield commented on config/settings.yml
> +  chatbot_openai_gpt4_url: "https://api.openai.com/v1/chat/completions"
I still don't understand why we need a definition per model?  If it changes per model then we should require the administrator to update the URL at the same time.

2023-08-14 15:43 UTC, fokx commented on config/locales/server.en.yml
> +    chatbot_openai_gpt4_url: "Modify it if you want to use GPT 4 by Azure, e.g. https://custom-domain.openai.azure.com/openai/deployments/DEPLOYMENT)."
Yeah, I agree. One place for setting the URL of the current model used is enough. Admins can record their deployment URLs elsewhere anyway.

2023-08-14 15:44 UTC, fokx commented on config/settings.yml
> +  chatbot_openai_gpt4_url: "https://api.openai.com/v1/chat/completions"
I agree with you.

2023-08-15 07:17 UTC, merefield commented on config/locales/server.en.yml
> +    chatbot_openai_gpt4_url: "Modify it if you want to use GPT 4 by Azure, e.g. https://custom-domain.openai.azure.com/openai/deployments/DEPLOYMENT)."
thanks @fokx.  One more change please: could we make the setting name just slightly more consistent: so like `chatbot_azure_open_ai_token` can we have `chatbot_azure_open_ai_model_url` ... then I think we are all but done here!  thx

2023-08-16 11:52 UTC, fokx commented on config/locales/server.en.yml
> +    chatbot_openai_gpt4_url: "Modify it if you want to use GPT 4 by Azure, e.g. https://custom-domain.openai.azure.com/openai/deployments/DEPLOYMENT)."
OK, I have renamed that option.

2023-08-16 18:57 UTC, merefield approved these changes
Thanks @fokx 🙏 I've made some minor changes to facilitate the merge.  Good work!

2023-08-16 19:20 UTC, merged