support custom Open AI model URL, not limited to Azure
merefield/discourse-chatbot pull request #32
Opened 2023-08-21 08:50 UTC by fokx

* rename `chatbot_azure_open_ai_model_url` to `chatbot_open_ai_model_custom_url` to support custom Open AI model URL, including but not limited to Azure
* merge `chatbot_azure_open_ai_token` option into `chatbot_open_ai_token`

2023-08-21 11:55 UTC, merefield requested changes

2023-08-21 12:17 UTC, fokx commented on lib/discourse_chatbot/bots/open_ai_bot.rb
>            config.api_type = :azure
Currently the only alternative `api_type` supported by `ruby-openai` is `azure`, so maybe we don't need to provide a setting option for it?

As for `api_version`, there are many variants according to [Azure OpenAI Service REST API reference](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference) and [Cognitive Services AzureOpenAI SDKs](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference). Different operations(e.g. Completions, Embeddings, Chat completions) have slightly different supported versions.
Even though I think the `api_version` works more on the *internal* side of the plugin or `ruby-openai`, I agree that it gives the user more flexibility by making this editable.

2023-08-21 12:52 UTC, fokx commented on lib/discourse_chatbot/bots/open_ai_bot.rb
>            config.api_type = :azure
Also, I think some initialization code in `open_ai_bot` and `open_ai_agent` are duplicated. I think it can be moved to super class `Bot`.

2023-08-22 10:52 UTC, merefield commented on lib/discourse_chatbot/bots/open_ai_bot.rb
>            config.api_type = :azure
love that idea, yes!

2023-08-22 11:15 UTC, merefield approved these changes

2023-08-22 11:23 UTC, merged